feat: chat functionality with emojis added
AdamGulmantowicz/memeking pull request #13
Opened 2023-06-04 19:06 UTC by PTRG01

2023-06-11 18:13 UTC, AdamGulmantowicz requested changes
It could be good to remove leftovers, wrap functions in `useCallback`, add translations and also move functions from js to separate declarations to increase redability.

2023-06-11 18:13 UTC, AdamGulmantowicz commented on apps/client/src/app/components/chat/chat.tsx
> +    const textarea = document.getElementById('textarea');
This is not the way how to use reference to DOM element. Please see `useRef` hook in react docs.

2023-06-11 18:13 UTC, AdamGulmantowicz commented on apps/client/src/app/components/chats/chats.module.css
> +  bottom: 4rem;
Why it's 4rem?

2023-06-11 18:13 UTC, AdamGulmantowicz commented on apps/client/src/app/components/chats/chats.tsx
> +    <div className={styles['chat-container']}>
What if there are no chats?

2023-06-11 18:13 UTC, AdamGulmantowicz commented on apps/client/src/app/components/following-list/following-list.tsx
> +                }}
Why it's typed void?

2023-06-11 18:13 UTC, AdamGulmantowicz commented on apps/client/src/app/components/test-component/test-component.tsx
> +      <h1>Welcome to TestComponent!</h1>
I think it's unnecessary.

2023-06-22 11:05 UTC, PTRG01 commented on apps/client/src/app/components/chats/chats.tsx
> +    <div className={styles['chat-container']}>
no chats message added to chats-list - chats component serves only as display container for chat windows

2023-07-04 19:59 UTC, AdamGulmantowicz commented on apps/client/src/app/components/message/message.tsx
> +  const formattedDate = `${dateObj.toLocaleString('en-US', {
You could `useMemo`

2024-01-17 19:04 UTC, merged