Feed
AdamGulmantowicz/memeking pull request #16
Opened 2023-12-21 22:42 UTC by PTRG01

2023-12-23 19:33 UTC, AdamGulmantowicz requested changes
In general look through all files and check:
- if anything in file is still used(you can use reference extension for vscode)
- any unused imports vars should be removed(you can adjust eslint config to show you all places with this issue)
- all places where `boolProp={true}` is set are in most cases unncecessary, you can adjust in eslint to help you remove this issue
- functions should be moved outside of JSX
- router need refactor, we should get rid of not authed user in application
- look into PrivateRoute component, probably whole application without splash screen should be wrapped in it
- all actions names should have enums
- all url should be moved to objects

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/posts/post/post.tsx
> +  groupsData?: IGroup[] | null;
Rename to `group`

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/posts/post-form/post-form.tsx
- Cleanup
- `useMemo` & `useCallback`
- missing translations
- unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/posts/post-list/post-list.tsx
> +              <Post post={post} groupsData={null} />
Maybe `groupsData` should be optional, and you shoud not set it to null.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/posts/post-list/post-list.tsx
- Cleanup

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/user-list/user-list.tsx
- Cleanup
- `useMemo` & `useCallback`

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/user-list-item-inline/user-list-item-inline.tsx
- Cleanup
- `useMemo` & `useCallback`

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/user-search/user-search.tsx
- Cleanup
- `useMemo` & `useCallback`
- missing translations
- unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/components/vote-bar/vote-bar.tsx
- Cleanup
- `useMemo` & `useCallback`
- missing translations
- unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/auth-provider/auth-provider.interface.ts
> +    overrideId?: string | undefined
Why this ovverride is necessary. Don't type as undefined, make this arg optional.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-provider/chat-provider.interface.ts
> +  followersSearchList: IUser[] | [];
Why it's empty array?

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-provider/chat-reducer.ts
All action names should be moved to Enum and reused accross application.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/auth-provider/auth-reducer.ts
All action types should be moved to Enum and reused accross app.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-window-provider/chat-window-provider.interface.ts
> +  currentChatUsers: IUser[] | IChat[] | null;
Why chat is passed here? It shouldn't be

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-window-provider/chat-window-provider.tsx
> +  chatId: '',
If you are using null for no value, then empty strings should be removed

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-window-provider/chat-window-provider.tsx
> +    pb.collection('messages').subscribe('*', async (e) => {
You should check all subscriptions and add cleanup function to unsubscribe on unmount

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-window-provider/chat-window-reducer.ts
> +export interface IChatWindowState {
Make some common type, because these values are repeated.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/chat-window-provider/chat-window-reducer.ts
All action names should be in Enum and reused in app

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/comment-provider/comment-provider.tsx
> +    pb.collection('comments').subscribe('*', async (e) => {
Add check for subscriptions and try to unsubscribe on unmount.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/feed-provider/feed-provider.tsx
> +  children: React.ReactNode;
You can extend PropsWithChildren interface when you want to use

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/feed-provider/feed-provider.tsx
- Cleanup

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/post-provider/post-provider.interface.ts
Remove eslint comments

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/post-provider/post-provider.tsx
Check subscriptions, remove console logs.

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/contexts/post-provider/post-reducer.ts
Create and reuse enum with action names

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/hooks/pb-utils.ts
> +    const [result, setResult] = useState<T[] | null>(null);
Maybe result should be renamed to `list`?

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/layouts/header/header.tsx
Cleanup and eslint comments. Remove unused vars, adjust menu and translatiosn

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/layouts/navbar/navbar.tsx
Move url to global object, cleanup

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/layouts/sidebar/sidebar.tsx
Cleanup

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/feed/feed.tsx
> +        {!groupFeed ? <ContentFormBar onPostClick={handleToggleForm} /> : null}
Simplify check, clear comments, `useCallback`

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/group/group.tsx
Unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/group/group.tsx
> +  if (groupId === undefined) return null;
Console log and unnecessary check for `=== undefined` could be simplified to `if (!val)`

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/groups/groups.tsx
Unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/home/home.tsx
Unused types

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/screens/profile/profile.tsx
Translations and types, unused variables

2023-12-23 19:33 UTC, AdamGulmantowicz commented on apps/client/src/app/app.tsx
I think we should not allow not logged in user to visit application. App should behave more like facebook/instagram, and we should sail away from 9gag model. This will simplify routing, and remove bugs with not logged checking forbidden pages

2023-12-23 19:33 UTC, AdamGulmantowicz requested changes
In general look through all files and check:
- if anything in file is still used(you can use reference extension for vscode)
- any unused imports vars should be removed(you can adjust eslint config to show you all places with this issue)
- all places where `boolProp={true}` is set are in most cases unncecessary, you can adjust in eslint to help you remove this issue
- functions should be moved outside of JSX
- router need refactor, we should get rid of not authed user in application
- look into PrivateRoute component, probably whole application without splash screen should be wrapped in it
- all actions names should have enums
- all url should be moved to objects

2023-12-30 18:24 UTC, PTRG01 commented on apps/client/src/app/components/comments/comment-bar/comment-bar.tsx
> +        onSubmit={form.onSubmit((values) =>
Not sure if it can be extracted, causes reload when not structured this way.

2024-01-17 15:49 UTC, AdamGulmantowicz approved these changes

2024-01-17 19:04 UTC, merged